export { TECHS, PROJECTS, SOCIAL_MEDIA };

const JVICTOR_JS_TEXT_MENTION_HTML = '<a href="https://github.com/jvictorjs" target="_blank"><strong class="blue--text">@jvictorjs</strong></a>';

const SOCIAL_MEDIA = [
  { name: "github", url: "https://github.com/jvictorjs", icon: "mdi-github", profile: "jvictorjs", tooltip: "GitHub profile" },
  { name: "twitter", url: "https://twitter.com/jvictor_js", icon: "mdi-twitter", profile: "@jvictor_js", tooltip: "Twitter profile" },
  { name: "portfolio", url: "https://portfolio.jvictor.com.br", icon: "mdi-briefcase", profile: "Porfolio", tooltip: "Portfolio web page" },
  { name: "youtube", url: "https://www.youtube.com/user/jvwrCIN", icon: "mdi-youtube", profile: "YouTube", tooltip: "My YouTube Channel" },
  {
    name: "linkedin",
    url: "https://www.linkedin.com/in/joão-victor-ramos-6570a21b7/",
    icon: "mdi-linkedin",
    profile: "LinkedIn",
    tooltip: "LinkedIn profile",
  },
  {
    name: "learn",
    url: "https://courses.jvictor.com.br",
    icon: "mdi-school",
    profile: "Course",
    tooltip: "Learn JavaScript with my video lessons",
  },
];

const PROJECTS = [
  {
    name: "TremdGol.com",
    nameFull: "TremdGol.com",
    description: " description  description  description  description  description  description  description ",
    language: "English",
    languageSymbol: "EN",
    urlLabel: "tremdgol.com",
    url: "https://tremdgol.com",
    githubRepoURL: "https://github.com/jvictorjs/tremdgol",
    youtubeDemoURL: "https://www.youtube.com/watch?v=2kQNpB26RIQ",
    imgFileName: "project-tremdgol.com.png",
    techsNamesToShowTag: ["Vue", "Vuetify", "REST APIs", "Canvas"],
    allTechs: ["Vue", "Vuetify", "REST APIs", "Canvas"],
  },
  {
    name: "My Course Platform",
    nameFull: "My Course Platform",
    description: " description  description  description  description  description  description  description ",
    language: "English<br>Lessons content: Brazilian Portuguese audio with English subtitles",
    languageSymbol: "EN/PT",
    urlLabel: "course.jvictor.com.br",
    url: "https://courses.jvictor.com.br",
    githubRepoURL: "https://github.com/jvictorjs/courses-platform",
    youtubeDemoURL: "",
    imgFileName: "project-my-course-platform.png",
    techsNamesToShowTag: ["React", "Vite", "GraphQL", "Apollo Client", "codegen"],
    allTechs: ["React", "Vite", "GraphQL", "Apollo Client", "codegen"],
  },
  {
    name: "TremdGol Android App",
    nameFull: "TremdGol Android App",
    description: " description  description  description  description  description  description  description ",
    language: "English",
    languageSymbol: "EN",
    urlLabel: "Google Play Store download",
    url: "https://play.google.com/store/apps/details?id=com.bolanarede.tremdgol_free",
    githubRepoURL: "https://github.com/jvictorjs/tremdgol-app",
    youtubeDemoURL: "",
    imgFileName: "playstore-tremdgol-free-screenshot.png",
    techsNamesToShowTag: ["React", "React Native", "REST APIs", "Expo", "Android Studio"],
    allTechs: ["React", "React Native", "REST APIs", "Expo", "Android Studio"],
  },
  {
    name: "Skills (this page)",
    nameFull: "Skills (this page)",
    description: " description  description  description  description  description  description  description ",
    language: "English",
    languageSymbol: "EN",
    urlLabel: "skills.jvictor.com.br",
    url: "https://skills.jvictor.com.br",
    githubRepoURL: "https://github.com/jvictorjs/skills-word-cloud",
    youtubeDemoURL: "",
    imgFileName: "project-skills.png",
    techsNamesToShowTag: ["Vue", "Vuetify", "Material Design Icons", "Flexbox", "CSS", "Flexbox", "Certbot SSL"],
    allTechs: [
      "Javascript",
      "HTML",
      "CSS",
      "Vue",
      "Vuetify",
      "Material Design Icons",
      "Flexbox",
      "CSS",
      "Flexbox",
      "Certbot SSL",
      "JSON Server",
      "PuTTy",
      "Ubuntu Linux",
      "NGINX",
      "Digital Ocean",
      "Git",
      "GitHub",
      "Certbot SSL",
      "Vim",
    ],
  },
  {
    name: "TremdGol backend",
    nameFull: "TremdGol backend (soccer stats api)",
    description: " description  description  description  description  description  description  description ",
    language: "English",
    languageSymbol: "EN",
    urlLabel: "api.tremdgol.com",
    url: "https://api.tremdgol.com",
    githubRepoURL: "https://github.com/jvictorjs/tremdgol-backend",
    youtubeDemoURL: "",
    imgFileName: "project-tremdgol-backend.png",
    techsNamesToShowTag: ["JSON Server", "PuTTy", "Ubuntu Linux", "NGINX", "Digital Ocean", "Git", "GitHub", "Certbot SSL"],
    allTechs: [
      "JavaScript",
      "HTML",
      "CSS",
      "JSON Server",
      "PuTTy",
      "Ubuntu Linux",
      "NGINX",
      "Digital Ocean",
      "Git",
      "GitHub",
      "Certbot SSL",
      "Certbot SSL",
      "JSON Server",
      "Google Apps Script",
      "PuTTy",
      "Ubuntu Linux",
      "NGINX",
      "Digital Ocean",
      "Git",
      "GitHub",
      "Certbot SSL",
      "Vim",
    ],
  },
  {
    name: "Avalia ME",
    nameFull: "Avalia ME",
    description: "sistema para avaliação de servidores do Ministério da economia (10k+ users)",
    language: "Brazilian Portuguese",
    languageSymbol: "PT",
    urlLabel: "avalia.economia.gov.br",
    url: "https://avalia.economia.gov.br",
    githubRepoURL: "",
    youtubeDemoURL: "",
    imgFileName: ".png",
    techsNamesToShowTag: ["Vue", "Vuetify"],
    allTechs: ["Vue", "Vuetify"],
  },
  {
    name: "Fundo a Fundo Dashboard",
    nameFull: "Fundo a Fundo Dashboard",
    description: "Painel criado com Qlik Sense para o Ministério da Economia do Brasil.",
    language: "Brazilian Portuguese",
    languageSymbol: "PT",
    urlLabel: "painelfundoafundo.economia.gov.br",
    url: "https://painelfundoafundo.economia.gov.br",
    githubRepoURL: "",
    youtubeDemoURL: "https://www.youtube.com/watch?v=xm1f4tRW0Sg",
    imgFileName: "project-painel-fundo-a-fundo.png",
    techsNamesToShowTag: ["Qlik Sense", "HTML", "CSS", "JavaScript"],
    allTechs: ["Qlik Sense", "HTML", "CSS", "JavaScript"],
  },
  {
    name: "Bola na Rede",
    nameFull: "Bola na Rede",
    description: " soccer live stats + tv matches guide ",
    language: "Brazilian Portuguese",
    languageSymbol: "PT",
    urlLabel: "bolanarede.net.br",
    url: "https://bolanarede.net.br",
    githubRepoURL: "https://github.com/jvictorjs/bolasite",
    youtubeDemoURL: "",
    imgFileName: ".png",
    techsNamesToShowTag: ["Angular", "TypeScript", "REST APIs", "Chart.js"],
    allTechs: ["Angular", "TypeScript", "REST APIs", "Chart.js"],
  },
  {
    name: "Medicine Reminder",
    nameFull: "Medicine Reminder (Telegram bot)",
    description: "A useful chatbot that reminds you when it is time to take that pill. This is one of many telegram bots I created.",
    language: "Brazilian Portuguese",
    languageSymbol: "PT",
    urlLabel: "",
    url: "",
    githubRepoURL: "https://github.com/jvictorjs/repositories-readmes/tree/main/en/medicine-reminder-telegram-chatbot",
    youtubeDemoURL: "",
    imgFileName: "project-medicine-reminder.jpg",
    techsNamesToShowTag: ["Google Apps Script", "Telegram Bots API", "REST APIs", "JavaScript"],
    allTechs: ["Google Apps Script", "Telegram Bots API", "REST APIs", "JavaScript"],
  },
  {
    name: "Portfolio page",
    nameFull: "Portfolio page",
    description: " description ",
    language: "English",
    languageSymbol: "EN",
    urlLabel: "portfolio.jvictor.com.br",
    url: "https://portfolio.jvictor.com.br",
    githubRepoURL: "https://github.com/jvictorjs/portfolio",
    youtubeDemoURL: "",
    imgFileName: "project-portfolio.png",
    techsNamesToShowTag: ["Angular", "TypeScript", "REST APIs", "Socket.io"],
    allTechs: ["Angular", "TypeScript", "REST APIs", "Socket.io"],
  },
  {
    name: "Telegram Web Clone",
    nameFull: "Telegram Web Clone",
    description: " description  description  description  description  description  description  description ",
    language: "English",
    languageSymbol: "EN",
    urlLabel: "jvictor.com.br",
    url: "https://jvictor.com.br",
    githubRepoURL: "https://github.com/jvictorjs/telegram-clone",
    youtubeDemoURL: "https://youtu.be/Nm9cWR95-hY",
    imgFileName: "project-telegram-clone.png",
    techsNamesToShowTag: ["Vue", "Vuetify", "Material Design Icons", "Flexbox", "CSS"],
    allTechs: [
      "Javascript",
      "HTML",
      "CSS",
      "Vue",
      "Vuetify",
      "Material Design Icons",
      "Flexbox",
      "CSS",
      "Flexbox",
      "Certbot SSL",
      "JSON Server",
      "PuTTy",
      "Ubuntu Linux",
      "NGINX",
      "Digital Ocean",
      "Git",
      "GitHub",
      "Certbot SSL",
      "Vim",
    ],
  },
];

const TECHS = [
  {
    name: "HTML",
    classType: 1,
    expYears: 5,
    skillLevel: 2,
    top: "15%",
    left: "67%",
    flags: { thisProj: true, pro: true, personal: true },
    relatedContent: [{ a: "HTML MDN Web DOCs", href: "https://developer.mozilla.org/en-US/docs/Web/HTML" }],
    projectsAvailable: [],
  },
  {
    name: "Material Design Icons",
    classType: 4,
    expYears: 1,
    skillLevel: 2,
    top: "27%",
    left: "78%",
    flags: { thisProj: true, pro: true, personal: true },
  },
  {
    name: "Phosphor Icons",
    classType: 5,
    expYears: 0,
    skillLevel: 2,
    top: "33%",
    left: "80%",
    flags: { thisProj: false, pro: true, personal: true },
  },
  { classType: 5, expYears: 0, skillLevel: 2, top: "8%", left: "77%", flags: { thisProj: false, pro: false, personal: true }, name: "Canvas" },
  { classType: 5, expYears: 1, skillLevel: 2, top: "16%", left: "81%", flags: { thisProj: false, pro: false, personal: true }, name: "Audio" },
  { classType: 5, expYears: 1, skillLevel: 2, top: "10%", left: "86%", flags: { thisProj: false, pro: false, personal: true }, name: "Markdown" },

  { classType: 2, expYears: 5, skillLevel: 2, top: "62%", left: "34%", flags: { thisProj: false, pro: true, personal: true }, name: "REST APIs" },
  { classType: 4, expYears: 2, skillLevel: 1, top: "75%", left: "35%", flags: { thisProj: false, pro: false, personal: true }, name: "Twitter API" },
  {
    classType: 3,
    expYears: 5,
    skillLevel: 3,
    top: "69%",
    left: "33%",
    flags: { thisProj: false, pro: false, personal: true },
    name: "Telegram Bots API",
  },
  { classType: 4, expYears: 2, skillLevel: 1, top: "56%", left: "35%", flags: { thisProj: false, pro: false, personal: true }, name: "JSON Server" },
  { classType: 5, expYears: 5, skillLevel: 2, top: "64%", left: "24%", flags: { thisProj: false, pro: false, personal: true }, name: "HTTP methods" },

  { classType: 3, expYears: 5, skillLevel: 2, top: "9%", left: "2%", flags: { thisProj: false, pro: false, personal: true }, name: "Google Sheets" },
  {
    classType: 2,
    expYears: 5,
    skillLevel: 3,
    top: "16%",
    left: "8%",
    flags: { thisProj: false, pro: false, personal: true },
    name: "Google Apps Script",
  },
  { classType: 5, expYears: 5, skillLevel: 3, top: "23%", left: "23%", flags: { thisProj: false, pro: false, personal: true }, name: "Triggers" },
  { classType: 5, expYears: 3, skillLevel: 3, top: "11%", left: "17%", flags: { thisProj: false, pro: false, personal: true }, name: "Automation" },
  { classType: 5, expYears: 5, skillLevel: 3, top: "4%", left: "11%", flags: { thisProj: false, pro: false, personal: true }, name: "Custom Menus" },
  { classType: 5, expYears: 5, skillLevel: 2, top: "11%", left: "29%", flags: { thisProj: false, pro: false, personal: true }, name: "Web Apps" },

  {
    name: "JavaScript",
    classType: 1,
    expYears: 5,
    skillLevel: 2,
    top: "35%",
    left: "18%",
    flags: { thisProj: true, pro: true, personal: true },
    relatedContent: [{ a: "JavaScript MDN Web DOCs", href: "https://developer.mozilla.org/en-US/docs/Web/JavaScript" }],
    projectsAvailable: [],
  },
  {
    name: "DOM Manipulation",
    classType: 5,
    expYears: 1,
    skillLevel: 2,
    top: "42%",
    left: "38%",
    flags: { thisProj: false, pro: true, personal: true },
  },
  { classType: 5, expYears: 1, skillLevel: 2, top: "28%", left: "30%", flags: { thisProj: false, pro: false, personal: true }, name: "Events" },
  { classType: 5, expYears: 2, skillLevel: 2, top: "46%", left: "22%", flags: { thisProj: false, pro: false, personal: true }, name: "Promises" },
  { classType: 3, expYears: 2, skillLevel: 2, top: "46%", left: "9%", flags: { thisProj: false, pro: false, personal: true }, name: "Node.js" },
  { classType: 4, expYears: 2, skillLevel: 2, top: "55%", left: "18%", flags: { thisProj: false, pro: false, personal: true }, name: "Express.js" },
  { classType: 3, expYears: 2, skillLevel: 2, top: "32%", left: "8%", flags: { thisProj: false, pro: false, personal: true }, name: "Chart.js" },
  { classType: 3, expYears: 1, skillLevel: 1, top: "25%", left: "37%", flags: { thisProj: false, pro: false, personal: true }, name: "TypeScript" },
  { classType: 5, expYears: 2, skillLevel: 2, top: "48%", left: "30%", flags: { thisProj: false, pro: false, personal: true }, name: "Axios" },

  { classType: 4, expYears: 1, skillLevel: 1, top: "30%", left: "56%", flags: { thisProj: false, pro: false, personal: true }, name: "Angular" },

  { classType: 3, expYears: 2, skillLevel: 1, top: "9%", left: "43%", flags: { thisProj: false, pro: false, personal: true }, name: "React Native" },
  { classType: 2, expYears: 2, skillLevel: 1, top: "14%", left: "52%", flags: { thisProj: false, pro: false, personal: true }, name: "React" },
  { classType: 5, expYears: 2, skillLevel: 1, top: "4%", left: "40%", flags: { thisProj: false, pro: false, personal: true }, name: "Expo" },
  {
    classType: 5,
    expYears: 1,
    skillLevel: 1,
    top: "4%",
    left: "53%",
    flags: { thisProj: false, pro: false, personal: true },
    name: "Android Studio",
  },
  {
    name: "Vite",
    expYears: 0,
    classType: 5,
    top: "34%",
    left: "45%",
    flags: { thisProj: false, pro: false, personal: true },
    projectsAvailable: [],
  },

  { classType: 2, expYears: 1, skillLevel: 2, top: "43%", left: "57%", flags: { thisProj: true, pro: true, personal: true }, name: "Vue" },
  { classType: 3, expYears: 1, skillLevel: 2, top: "49%", left: "62%", flags: { thisProj: true, pro: true, personal: true }, name: "Vuetify" },
  { classType: 5, expYears: 1, skillLevel: 1, top: "43%", left: "52%", flags: { thisProj: false, pro: false, personal: true }, name: "Vuex" },
  { classType: 5, expYears: 1, skillLevel: 2, top: "50%", left: "51%", flags: { thisProj: false, pro: false, personal: true }, name: "Vue router" },

  {
    name: "CSS",
    classType: 1,
    expYears: 5,
    skillLevel: 2,
    top: "55%",
    left: "77%",
    flags: { thisProj: true, pro: true, personal: true },
    relatedContent: [{ a: "HTML MDN Web DOCs", href: "https://developer.mozilla.org/pt-BR/docs/Web/CSS" }],
    projectsAvailable: [],
  },
  { classType: 4, expYears: 0, skillLevel: 1, top: "46%", left: "83%", flags: { thisProj: false, pro: false, personal: true }, name: "Tailwind CSS" },
  { classType: 5, expYears: 0, skillLevel: 1, top: "65%", left: "86%", flags: { thisProj: false, pro: false, personal: true }, name: "SASS" },
  { classType: 5, expYears: 2, skillLevel: 2, top: "44%", left: "75%", flags: { thisProj: true, pro: true, personal: true }, name: "Flexbox" },
  { classType: 4, expYears: 2, skillLevel: 2, top: "66%", left: "73%", flags: { thisProj: true, pro: false, personal: true }, name: "Transitions" },
  { classType: 5, expYears: 0, skillLevel: 2, top: "59%", left: "69%", flags: { thisProj: true, pro: false, personal: true }, name: "Variables" },

  {
    name: "GraphQL",
    classType: 4,
    expYears: 0,
    skillLevel: 1,
    top: "79%",
    left: "50%",
    flags: { thisProj: false, pro: false, personal: true },
    relatedContent: [],
    projectsAvailable: [],
  },
  {
    name: "Apollo Client",
    classType: 5,
    expYears: 0,
    skillLevel: 1,
    top: "75%",
    left: "52%",
    flags: { thisProj: false, pro: false, personal: true },
    relatedContent: [],
    projectsAvailable: [],
  },
  {
    name: "codegen",
    classType: 5,
    expYears: 0,
    skillLevel: 1,
    top: "84%",
    left: "48%",
    flags: { thisProj: false, pro: false, personal: true },
    relatedContent: [],
    projectsAvailable: [],
  },

  {
    name: "Pentaho Data Integration",
    classType: 3,
    expYears: 5,
    skillLevel: 3,
    top: "91%",
    left: "62%",
    flags: { thisProj: false, pro: true, personal: true },
    description: `<i><a href="https://help.hitachivantara.com/Documentation/Pentaho/9.0/Setup/Pentaho_Data_Integration_(PDI)_tutorial" target="_blank"><strong class="blue--text">Pentaho Data Integration (PDI)</strong></a> provides the Extract, Transform, and Load (ETL) capabilities that facilitate the process of capturing, cleansing, and storing data.</i>`,
    relatedContent: [
      { a: "Pentaho Docs", href: "https://help.hitachivantara.com/Documentation/Pentaho/9.0/Setup/Pentaho_Data_Integration_(PDI)_tutorial" },
    ],
    projectsAvailable: [],
  },
  { classType: 5, expYears: 3, skillLevel: 1, top: "86%", left: "88%", flags: { thisProj: false, pro: true, personal: false }, name: "Power BI" },
  { classType: 5, expYears: 3, skillLevel: 1, top: "91%", left: "90%", flags: { thisProj: false, pro: true, personal: false }, name: "Qlik Sense" },
  { classType: 2, expYears: 5, skillLevel: 2, top: "83%", left: "63%", flags: { thisProj: false, pro: true, personal: true }, name: "SQL" },
  { classType: 5, expYears: 2, skillLevel: 1, top: "84%", left: "80%", flags: { thisProj: false, pro: true, personal: true }, name: "SQLite" },
  { classType: 5, expYears: 1, skillLevel: 2, top: "84%", left: "71%", flags: { thisProj: false, pro: true, personal: false }, name: "SQL Server" },
  { classType: 5, expYears: 5, skillLevel: 2, top: "78%", left: "67%", flags: { thisProj: false, pro: true, personal: false }, name: "PostgreSQL" },
  { classType: 5, expYears: 1, skillLevel: 2, top: "90%", left: "56%", flags: { thisProj: false, pro: true, personal: false }, name: "DBeaver" },

  { classType: 3, expYears: 2, skillLevel: 2, top: "87%", left: "37%", flags: { thisProj: true, pro: true, personal: true }, name: "Git" },
  { classType: 4, expYears: 2, skillLevel: 2, top: "91%", left: "40%", flags: { thisProj: true, pro: true, personal: true }, name: "GitHub" },

  { classType: 5, expYears: 1, skillLevel: 1, top: "64%", left: "13%", flags: { thisProj: false, pro: false, personal: true }, name: "Socket.io" },

  { classType: 5, expYears: 2, skillLevel: 1, top: "53%", left: "8%", flags: { thisProj: false, pro: false, personal: true }, name: "NPM" },
  { classType: 5, expYears: 2, skillLevel: 2, top: "73%", left: "18%", flags: { thisProj: true, pro: false, personal: true }, name: "NGINX" },
  { classType: 3, expYears: 5, skillLevel: 2, top: "78%", left: "6%", flags: { thisProj: true, pro: false, personal: true }, name: "Ubuntu Linux" },
  { classType: 5, expYears: 5, skillLevel: 2, top: "79%", left: "2%", flags: { thisProj: false, pro: false, personal: true }, name: "Vim" },
  { classType: 5, expYears: 5, skillLevel: 2, top: "71%", left: "9%", flags: { thisProj: true, pro: false, personal: true }, name: "PuTTy" },
  { classType: 4, expYears: 1, skillLevel: 2, top: "91%", left: "24%", flags: { thisProj: false, pro: false, personal: true }, name: "Netlify" },
  { classType: 3, expYears: 2, skillLevel: 2, top: "86%", left: "10%", flags: { thisProj: true, pro: false, personal: true }, name: "Digital Ocean" },
  { classType: 5, expYears: 2, skillLevel: 1, top: "86%", left: "3%", flags: { thisProj: true, pro: false, personal: true }, name: "WinSCP" },
  { classType: 5, expYears: 2, skillLevel: 2, top: "80%", left: "20%", flags: { thisProj: true, pro: false, personal: true }, name: "Certbot SSL" },
  { classType: 5, expYears: 2, skillLevel: 2, top: "72%", left: "3%", flags: { thisProj: false, pro: false, personal: true }, name: "PM2" },
];
